### ISSUE TITLE
notes tab

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#74]
Carlo, when a user downloads gcode/stls, will they get a .txt doc included?  I'd like for this document to include all data that the user inputs into LF.  Additionally, can we make this txt file viewable with a pull out tab on the right side of the screen? See the sketch I did with the tab designs.  The user should also be able to take notes on this document at any point while using LF.

**Comment by luzlab** [comment]
Just sketch out what you're thinking as far as the pull out tab. That's this issue (making the UX). I'll add a couple of issues for (1) making a txt file with the relevant info is another issue (be sure to include a sample file of what you want) and (2) adding that text file to the zip.

And yes, this is all possible. It's just a matter of prioritization - what's more important? This or supporting 3rd party designs? Providing a UX for designers (not doctors) to upload and specify their designs?

I want to move away from a "stream-of-conciousness" development planning mode, to something a little more deliberate...

**Comment by luzlab** [comment]
Just reread this... so the dynamic editing of the notes tab is also possible, it just adds complexity and scope. Can we break out the editing of the file into a separate issue?

Also, it's good to attach the drawing to this issue (or at least include a reference to the other issue with the drawings) so it's obvious. Just imagine when/if we have developers from Autodesk working on this - they should have everything they need to crank on an issue right at hand, otherwise, they're not going to work on any thing. Trust me, @kaitlynhova deserves a sainthood for not losing it at all the changes thrown at her...

**Comment by hobe12** [comment]
Sorry, my wonderful code friends.  I will do my best to curb my streams of consciousness.  @kaitlynhova, if you want to smack me, I'll make sure to get into the office on Friday.  

In all seriousness, thanks for the feedback.  Don't hesitate to criticize.  I'm from NYC- I can take it.

**Comment by kaitlynhova** [comment]
Closing and adding to [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out
