### ISSUE TITLE
Log in page

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#82]
After logging in, users are redirected to the design tool.

Very little text.

Tasks.
- [x] Pixel perfect design [ 1440px wide ]  that includes - @hobe12  (10 hours)
    - [x] Add login area
    - [x] Add Title + description
    - [x] Favicon 
    - [x] Link back to main ECF website: "learn more about limbforge"
- [x] Font end implementation of design ^^^ - @kaitlynhova (2 hours)
    - [x] Remove basic HTML password protection in favor of sign in page (see below for current traffic jam)

<img width="769" alt="screenshot 2017-03-12 16 27 51" src="https://cloud.githubusercontent.com/assets/5185511/23837214/042023a4-0742-11e7-9d14-56cafbf3d51c.png">

**Comment by luzlab** [comment]
For the favicon, check out tools like http://www.favicon.cc. There's also online tools for converting regular pictures to the special favicon format.

**Comment by hobe12** [comment]
Very quick first attempt
[favicon.ico.zip](https://github.com/limbforge/Limbforge/files/817538/favicon.ico.zip)

**Comment by kaitlynhova** [comment]
Got it! Things I had to modify:

1. The text was generally too small on the mockup. The smallest font we can use is 16px in order to fit with UX best practices so I made the smallest text 16px.
2. Since we will be dealing with sensitive medical info I'd strongly advise against a "keep me signed in" button. 
3. I think that this could be a general template I also updated the pages for signup, password reset, and password edit. 
4. I added a quick "sign out" button on the Limbforge top left on the Limbforge tool for quick sign out.
5. I needed to add some sort of check for spam since it looks like we want to remove the google reCaptcha tags. If we have problems with spam we should bring them back.
6. I removed the border radius on the form outline so that it was more consistent with the input boxes.

@hobe12 can you take a look at [staging1](https://limbforge-staging1.herokuapp.com/) and let me know what you think?
